### ISSUE TITLE
Vertically centering quote on homepage

### ISSUE THREAD

**Issue by ScottReinhard** [stillmuseum/patricia#101]
Small thing, but since this is front and center on the home page, I'd like it to be centered. It feels a bit off.
Preferably 50 px at the top of the quote, and 50 px underneath the source

![image](https://cloud.githubusercontent.com/assets/7491083/4517635/a56fa078-4c4a-11e4-88b9-95f7017758da.png)

**Comment by halfempty** [comment]
Done.
