### ISSUE TITLE
Responsive images using srcset

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#109]
@swambold6 It's here! The "solution" for responsive images:

http://alistapart.com/article/responsive-images-in-practice

The selling point is that it reduces the data downloaded to mobile devices, significantly improving load-time. And load-time is very important to mobile users. The article says:

> These sorts of reductions—40 percent, 70 percent, 90 percent—should stop you in your tracks. We’re trimming nearly two and a half megabytes off of every Retina iPhone load. Measure that in milliseconds or multiply it by thousands of pageviews, and you’ll see what all of the fuss is about.

I would rate this to-do as being of Medium complexity.

Note / i-device widths:

320
480
640
750
960
1125
1136
1242
1334
2001
2208

**Comment by halfempty** [comment]
Okay, this is done.

**Comment by halfempty** [comment]
@swambold6 I've come to realize I missed an aspect of this. Namely, `sizes="..."`. So, reopening...

**Comment by halfempty** [comment]
@swambold6 I *think* I've cracked it!!

**Comment by swambold6** [comment]
Yay!  Want to tell me about it?  Or will it be over my head?

On Tue, Mar 31, 2015 at 11:26 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @swambold6 <https://github.com/swambold6> I *think* I've cracked it!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/109#issuecomment-88354628>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 Okay, this is added!
