### ISSUE TITLE
Create tables that transform gracefully

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#110]
Guideline 5. Create tables that transform gracefully.

5.1 For data tables, identify row and column headers.

5.2 For data tables that have two or more logical levels of row or column headers, use markup to associate data cells and header cells.

**Comment by halfempty** [comment]
@swambold6 Our tables are both on the visit page -- Hours and Admission -- right? Are there others?

Honestly, I'm not even sure there are any problems with our tables. What's your understanding of the spec?

**Comment by swambold6** [comment]
Free Public Tours and Private Tours are tables, too:
http://clyffordstillmuseum.org/tours/

Yeah, I don't think there are probably any problems with our tables.  Are
there html labels we should be using that we're not?  Table, column, or row
titles, or something?

On Thu, Feb 5, 2015 at 12:54 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Our tables are both on the
> visit page -- Hours and Admission -- right? Are there others?
>
> Honestly, I'm not even sure there are any problems with our tables. What's
> your understanding of the spec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/110#issuecomment-73114682>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 Okay, done. Here's the reference I used:

http://webaim.org/techniques/tables/data

I had to add more `th`s. Also, converted `h3`s to `caption`s where I could.

**Comment by swambold6** [comment]
I don't see the caption tags.  What am I missing?
