### ISSUE TITLE
Ensure that pages featuring new technologies transform gracefully

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#111]
6.1 Organize documents so they may be read without style sheets. For example, when an HTML document is rendered without associated style sheets, it must still be possible to read the document.

6.3 Ensure that pages are usable when scripts, applets, or other programmatic objects are turned off or not supported. If this is not possible, provide equivalent information on an alternative accessible page.

**Comment by halfempty** [comment]
@swambold6 I actually think we're okay with this one. Do you recall us flagging anything specific?

**Comment by swambold6** [comment]
No, I think we're good here, too.  It's not like we're employing bleeding edge technologies, so I don't think we had anything to worry about in the first place.  On a more basic level, I've been reading a book on HTML and CSS, which provides some additional remarks on accessibility.  Everything I've come across we're already doing.

Yeah us!  (More so...Yeah you!)
