### ISSUE TITLE
Ensure direct accessibility of embedded user interfaces

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#112]
Guideline 8. Ensure direct accessibility of embedded user interfaces.  -  Medium

8.1 Make programmatic elements such as scripts and applets directly accessible or compatible with assistive technologies [Priority 1 if functionality is important and not presented elsewhere, otherwise Priority 2.]

**Comment by halfempty** [comment]
@swambold6 Do you recall if there were specific problems with this one? I can't think of anything we've done that might run afoul of this.

**Comment by swambold6** [comment]
I'm not aware of anything.

For the sake of covering our bases on this 508 compliance...are you aware of any online tool or site that runs an automatic assessment of this stuff?  Just thinking worst case:  we report to John we've taken care of everything, John independently comes across this tool (if it exists) and types in the CSM url, this online tool (credible or not) indexes the site and then tells John it's not compliant, and then John comes back to us.  It's a far-fetched scenario to be sure...but just for the sake of due diligence...

**Comment by halfempty** [comment]
@swambold6 There ARE automated tools out there (http://webaim.org/ would be one place to look), but they tend to be more of the "is the contrast high enough" variety. I'm not sure what they'd say regarding this particular test. The best testing is done by specialized techs, using the actual assistive technologies.

I'm going to label this as "done" but not "closed," cool?

**Comment by swambold6** [comment]
Yeah, sounds good.  I'll assign it to myself for a due diligence effort to come.
