### ISSUE TITLE
Use of categories for blog and events

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#113]

**Comment by halfempty** [comment]
@swambold6 Can we get more specific about how we'd like these to be used?

**Comment by swambold6** [comment]
Used in terms of how John will use them, or used in terms of how they will look on the front-end?

**Comment by halfempty** [comment]
@swambold6 On the front end. The back-end interface is what WP provides.

**Comment by halfempty** [comment]
@swambold6 Oh, PS. But yeah, also sort of conceptually-- what are categories "for" on this site?

**Comment by swambold6** [comment]
@ScottReinhard Do you have mock-ups showing the use/placement/design of tags and categories for the blog that you could resend to us?  Just want to be sure we're looking at the most recent intentions.

@halfempty So, yeah, conceptually...not sure I have that answer other than to say how tags and categories are used on other blogs, as a tool for finding related content.  I'd say whatever we do, we should plan for the possibility that they won't keep up with using them, and so may want to not show them if they're being left blank.  Would it help if I got a list of categories John would like to be using on the blog?  If it's easier to hash this out over the phone let me know.  I don't have any confidence I'm answering the question you're asking.

**Comment by halfempty** [comment]
@swambold6 PPS. Or even more to the point, is there an design pattern from the mockups that applies?

**Comment by halfempty** [comment]
@swambold6 PPPS. Ah, you were already there!

**Comment by halfempty** [comment]
![image](https://cloud.githubusercontent.com/assets/775543/6907767/9ffd7310-d6fe-11e4-89a5-b280531a12ca.png)

**Comment by halfempty** [comment]
Unexpectedly, tags are already in for blog posts! For instance:

https://clyffordstillmuseum.org/summer-reads

So this can just be closed, I think.

Also, I converted all the existing Post Categories to tags, so that's simpler now. John should feel empowered to tag away to his heart's content!
