### ISSUE TITLE
Exclude from Search

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#116]
@swambold6 I've noticed that there are pages like "Group Visit Request Received" that we don't want to appear in the search results. So I've installed a plugin called "Search Everything" to give us the ability to do this. It can also do other things. You should check it out! Settings -> Search Everything

**Comment by swambold6** [comment]
Will do!  Thanks!

On Mon, Mar 16, 2015 at 4:09 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> I've noticed that there are
> pages like "Group Visit Request Received" that we don't want to appear in
> the search results. So I've installed a plugin called "Search Everything"
> to give us the ability to do this. It can also do other things. You should
> check it out! Settings -> Search Everything
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/116>.
>



-- 
Best regards,
Sarah Wambold

swambold.com
