### ISSUE TITLE
Collection objects bug?

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#117]
The Collection Category panel won't stay visible.  I keep having to go in to Screen Options and check the box to make it visible.  Like over and over and over...  Can you take a look in to this?

**Comment by halfempty** [comment]
@swambold6 I really don't have many ideas. The taxonomy is defined in a standard way, and WP generates the UI...

**Comment by halfempty** [comment]
@swambold6 Ps. Is this happening on Dev, Live or both?

**Comment by swambold6** [comment]
Both.

**Comment by halfempty** [comment]
Found it. Was a bug in Advanced Custom Fields. From the release notes: 
 
> Core: Fixed bug where field group postboxes would disappear from post edit screen

**Comment by swambold6** [comment]
Good deal.  Thanks!

On Mon, Mar 30, 2015 at 6:41 PM, Marty Spellerberg <notifications@github.com
> wrote:

> Found it. Was a bug in Advanced Custom Fields. From the release notes:
>
> Core: Fixed bug where field group postboxes would disappear from post edit
> screen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/117#issuecomment-87887960>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
