### ISSUE TITLE
Collection on Homepage

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#119]
![screen shot 2015-03-31 at 10 39 10 am](https://cloud.githubusercontent.com/assets/775543/6924941/b0bdc13e-d7a1-11e4-9994-5dc7a488d4d2.png)

**Comment by halfempty** [comment]
@swambold6 Okay, please take a look:

https://dev.clyffordstillmuseum.org/

**Comment by swambold6** [comment]
John says looks good, but please change the order of the two groups so that Collection is on the left and Archives is on the right.

Then launch!

**Comment by halfempty** [comment]
okay, done!

**Comment by swambold6** [comment]
John loves it!  Thanks, and cheers!
