### ISSUE TITLE
Calendar Plugin Update

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#120]
@swambold6 As I mentioned, I've continued to go back and forth with the calendar plugin folks with the objective of updating our existing templates to the new version. We may have finally found success.

Could you do me a favor and take a close, QA-style look at the calendar on the dev site? Especially the event category listings. It's meant to work exactly like the live site.

Thanks!

**Comment by halfempty** [comment]
@swambold6 I would like to complete this plugin update this month. Will you have a chance to do that QA check on it? It should only take a couple of minutes.

**Comment by swambold6** [comment]
@halfempty:

Spoke to John, priorities are as follows:
- Calendar (bugs and grid...please advise about the order)
- Thumbnail cropping

According to my calculations, we have $3K ($1.5K left over in your hours, and the same in mine) in the budget for this work.  Are both doable within that budget?
