### ISSUE TITLE
Image Crops

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#121]
**John says:**

> Upon uploading a photo, right now the site auto-crops the square version that’s featured on our home page + Calendar + Archives + Collection pages. Quite often that square ends up looking not so great; sometimes it ends up looking downright strange. If I had to pick my number-one concern / pet peeve regarding the look of our site, this would be it. Too often it’s pretty much impossible to create an image that looks good both 2x1 and square. 

> I wonder if you can chat with Marty about this sometime soon if you haven’t already. Might there be a path to manually uploading the square version of an image, rather than always having an auto crop? Maybe something we can discuss in the hallways of the Palmer House this week!

**Comment by swambold6** [comment]
@halfempty So glad we talked about this!!!

John would like a second box for uploading the square crop / thumbnail image.

Is it possible to write into the code that if left blank, to use an WP-generated crop of the Featured Image field?

All make sense?

**Comment by halfempty** [comment]
Note to self. Template files implicated:

- [ ] parts/archivegird.php (csm_collection_thumbnail)
- [ ] parts/collectiongrid.php (csm_collection_thumbnail)
- [ ] parts/exhibition-thumbsquare.php (has_post_thumbnail/the_post_thumbnail)
- [ ] parts/home-archive.php (csm_collection_thumbnail)
- [ ] parts/home-blog.php (has_post_thumbnail/spellerberg_the_thumbnail)
- [ ] parts/home-collection.php (csm_collection_thumbnail)
- [ ] parts/home-events.php (has_post_thumbnai/spellerberg_the_thumbnail)
- [ ] parts/home-exhibition.php (has_post_thumbnail/spellerberg_the_thumbnail)
