### ISSUE TITLE
Couple of PHP warnings

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#125]
Poking through the logs I found these two minor warnings:

`Missing argument 2 for spellerberg_return_sp_date(), called in /var/www/vhosts/tgrz-bmxy.accessdomain.com/httpdocs/clyffordstillmuseum.org/wp-content/themes/patricia/functions/connections.php on line 248`

`array_reverse() expects parameter 1 to be array, null given in /var/www/vhosts/tgrz-bmxy.accessdomain.com/httpdocs/clyffordstillmuseum.org/wp-content/themes/patricia/page-exhibitions.php on line 116`

**Comment by swambold6** [comment]
I assume this isn't supposed to mean anything to me?

On Fri, Jun 26, 2015 at 11:45 AM, Marty Spellerberg <
notifications@github.com> wrote:

> Poking through the logs I found these two minor warnings:
>
> Missing argument 2 for spellerberg_return_sp_date(), called in
> /var/www/vhosts/
> tgrz-bmxy.accessdomain.com/httpdocs/clyffordstillmuseum.org/wp-content/themes/patricia/functions/connections.php
> on line 248
>
> array_reverse() expects parameter 1 to be array, null given in
> /var/www/vhosts/
> tgrz-bmxy.accessdomain.com/httpdocs/clyffordstillmuseum.org/wp-content/themes/patricia/page-exhibitions.php
> on line 116
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/125>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
Fixed
