### ISSUE TITLE
Event Export Links

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#126]
**Dean said:**

> Hi all — I noticed that each of the Biennial events have two buttons that allow you to put them in “Google Calendar” and “ICAL Export.”  Who else thinks this is a good idea? How hard would it be to do?

**Comment by halfempty** [comment]
@swambold6 Yeah, this is quick. I'll work on it right now.

**Comment by halfempty** [comment]
@swambold6 Okay, I've put them in like so:

![image](https://cloud.githubusercontent.com/assets/775543/8733564/f992d3a0-2bc9-11e5-85e9-7515dae88390.png)

Do you think they need to be differentiated, visually? Or do they work as-is?

**Comment by swambold6** [comment]
Looks great!  Amazing quick on this one!  I'll send it to John to see if he
has any changes.

Thanks, thanks, thanks!!!

On Thu, Jul 16, 2015 at 1:50 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Okay, I've put them in like so:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/775543/8733564/f992d3a0-2bc9-11e5-85e9-7515dae88390.png>
>
> Do you think they need to be differentiated, visually? Or do they work
> as-is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/126#issuecomment-122069370>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
