### ISSUE TITLE
Sidebar menu not appearing

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#128]
**@swambold6 says:**

> Can't figure out why not.
> https://clyffordstillmuseum.org/events/category/public-programs/
> https://clyffordstillmuseum.org/events/category/member-programs/
> The settings in Menus, Widget Areas, and Widgets seem right to me.  ?

**Comment by halfempty** [comment]
@swambold6 I'm also not exactly sure the problem. I recently updated the Sidebar plugin, so I first tried going back to the older version. But no luck.

I suspect it's the Events plugin not behaving in the normal WP way. This is something that's come up before. To determine this for-sure will take a bit of testing, so instead...

I've routed around the Sidebar plugin, for Event Categories only. Now, they are hard-coded to their own Widget Area, in which I've specified the "What's On" menu. 

I'd prefer to use the plugin everywhere, but hopefully this work  around is okay. Let me know what you think!

**Comment by swambold6** [comment]
Thanks for looking in to this. I recall having some issues with this in the
past. I guess it just doesn't want to play nice.

If I'm reading this correctly, we can still change what links appear in the
sidebar menu through the CMS (in Menus). The only thing that is hard coded
is the the menu that is set to appear in that Widget Area. Is that right?

On Wednesday, October 14, 2015, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> I'm also not exactly sure the
> problem. I recently updated the Sidebar plugin, so I first tried going back
> to the older version. But no luck.
>
> I suspect it's the Events plugin not behaving in the normal WP way. This
> is something that's come up before. To determine this for-sure will take a
> bit of testing, so instead...
>
> I've routed around the Sidebar plugin, for Event Categories only. Now,
> they are hard-coded to their own Widget Area, in which I've specified the
> "What's On" menu.
>
> I'd prefer to use the plugin everywhere, but hopefully this work around is
> okay. Let me know what you think!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/128#issuecomment-148210137>
> .
>


-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
Yes, it's the selection of the Widget Area that's now hard-coded to Event Categories

**Comment by halfempty** [comment]
@swambold6 I'll close this one. If you encounter any new issues with the sidebar, we can open a new ticket.
