### ISSUE TITLE
Links for homepage images

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#130]
**@swambold6 said:**

> Is there any easy way to add the functionality to be able to link an image to a url in the Home template?

**Comment by halfempty** [comment]
@swambold6 Okay, take a look? (I went ahead and linked the first one to Replicas, 'cause I guessed that's what you're up to)

**Comment by swambold6** [comment]
Great!  Thanks!

Mark as closed.  :)

On Thu, Nov 19, 2015 at 1:45 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Okay, take a look? (I went
> ahead and linked the first one to Replicas, 'cause I guessed that's what
> you're up to)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/130#issuecomment-158192710>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
