### ISSUE TITLE
Use of S/M/L?

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#132]
**@swambold6 said:**

> Can you break down for me the Small, Medium, and Large settings in terms of where they appear on the site?

**Comment by swambold6** [comment]
@halfempty This could be useful for the Be Still My Heart events, as well.  Let me know if you already sent this to me...

**Comment by halfempty** [comment]
@swambold6 Did a search in the code. Looks like only the homepage, to exclude small events.

**Comment by swambold6** [comment]
So, S, M, and L, are exactly the same, but S events do not appear on the
homepage.  That's the only distinction.  Is that right?

On Thu, Feb 4, 2016 at 7:33 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> Did a search in the code. Looks
> like only the homepage, to exclude small events.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/132#issuecomment-180163647>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 yes
