### ISSUE TITLE
Video channel

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#133]
**@swambold6 said:**

I’m curious about the Vimeo customization on this:

http://artistproject.metmuseum.org/

I don’t envision ours as a microsite experience or anything like that, but they’ve done some really interesting customization in both the player and the how the thing is embedded.  I want to know more…

**Comment by halfempty** [comment]
@swambold6 Taking a quick glance under the hood:

- They're using WordPress
- They're using MediaElement.js, which is for browser compatibility
- I'm seeing "moogaloop", which is the Vimeo API for doing flash players. This might be in the context of sending it to FB.
- I'm seeing some other JavaScript code, the name of which has been stripped out but I'm guessing it's Froogaloop, which is more Vimeo API

What I'm taking away from all this is that it's done using a technology stack similar to the one we would use. They did a large amount of work to get that clean, totally custom look, however.

**Comment by swambold6** [comment]
Thanks for looking in to this.

I haven't really wrapped my head around what makes sense for CSM, both in
terms of what this video channel needs to be (in terms of design, content,
features) or where (in terms of architecture).  If you have any thoughts,
let me know.

In the meantime, if you have a sense of how many hours the "large amount of
work to get that clean, totally custom look" would be, I'd be happy to have
that info.



On Fri, Dec 4, 2015 at 11:58 AM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Taking a quick glance under the
> hood:
>
>    - They're using WordPress
>    - They're using MediaElement.js, which is for browser compatibility
>    - I'm seeing "moogaloop", which is the Vimeo API for doing flash
>    players. This might be in the context of sending it to FB.
>    - I'm seeing some other JavaScript code, the name of which has been
>    stripped out but I'm guessing it's Froogaloop, which is more Vimeo API
>
> What I'm taking away from all this is that it's done using a technology
> stack similar to the one we would use. They did a large amount of work to
> get that clean, totally custom look, however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/133#issuecomment-162052185>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
