### ISSUE TITLE
Double Take on Homepage

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#134]
**@swambold6 says:**

As a last-minute push for the holidays, we're offering a 2-for-1 admission deal, which we'd like to display prominently on the homepage.

I've suggested something more image-based (see below).  If we went animated gif style (ala this MoMA email that was passed around in CSM circles a few weeks ago), will the WP media library handle an animated gif?  Are there any specs you would suggest for the designer?

https://connect.moma.org/pub/sf/FormLink?_ri_=X0Gzc2X%3DYQpglLjHJlYQGgzekDzglepmrXEtKOnazd4fcYLiyT0fzfFAWp1uITMAjuy0vKmq6OVXMtX%3DYQpglLjHJlYQGNNzc5LSJ8uuR3atzfeRY45ljjuozdX2URRLHriuIgoze8HtLSapGR&_ei_=EolaGGF4SNMvxFF7KucKuWNt4GRHVZil2Sb-8hLay21OUm2BG0Tm-h3BUXARChWpc5h588XD2oZ1P5ylXddd43gFiOl2xnY4Pp8jigu2DkSxjvTt.

**Comment by halfempty** [comment]
@swambold6, thinking about how to get this GIF on the homepage, 'cause right now the system makes automatically-generated JPGs for everything. Options include:

1. Hard-code this particular promotion
2. Create a checkbox that says something like "use original file"
3. Have it test if the file is a GIF and, if so, make sure to use it

Do you have a preference?

**Comment by swambold6** [comment]
I do not have a preference.  I don't foresee this becoming a habit.  So
whatever is easiest for you.

On Fri, Dec 4, 2015 at 11:14 AM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6>, thinking about how to get this
> GIF on the homepage, 'cause right now the system makes
> automatically-generated JPGs for everything. Options include:
>
>    1. Hard-code this particular promotion
>    2. Create a checkbox that says something like "use original file"
>    3. Have it test if the file is a GIF and, if so, make sure to use it
>
> Do you have a preference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/134#issuecomment-162038896>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 okay, done:

https://clyffordstillmuseum.org/

**Comment by halfempty** [comment]
@swambold6 PS. I did the file type detection thing, so GIFs will automatically work in the future

**Comment by swambold6** [comment]
Awesome!  Thanks.

It's pretty bold, eh?  Perhaps better than having the text at the top
though.  I hope.  McGinty Co did it for us.  Looks nice, but it's huge.

A question...will animated gifs work on every page of the website, or just
the Home template?

On Fri, Dec 4, 2015 at 11:42 AM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> PS. I did the file type
> detection thing, so GIFs will automatically work in the future
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/134#issuecomment-162047643>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 it should work in most places. (the change was made at a fairly low level in the code)

It looks good, IMO!

**Comment by swambold6** [comment]
We have another animated GIF to put on the site to temporarily promote an event. This should work just fine for the homepage (given the above), right? Will it also work to use an animated GIF for the featured image of the Event page?

**Comment by halfempty** [comment]
@swambold6 It should. It uses the same underlying method, to which we added the GIF functionality.

**Comment by swambold6** [comment]
Thanks, Marty!

On Wednesday, June 8, 2016, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> It should. It uses the same
> underlying method, to which we added the GIF functionality.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/134#issuecomment-224757421>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHJQdyHwuVeyFZEpAN42ziD_-O2PmyYwks5qJ0plgaJpZM4GvD2->
> .
>


-- 
Best regards,
Sarah Wambold

swambold.com
