### ISSUE TITLE
Chronological order for Related Events

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#135]
Could we add some logic into the Related Events so that they appear in chronological order from top to bottom?

Example here:
https://clyffordstillmuseum.org/event/music-in-the-galleries/2016-01-10/

Thanks!

**Comment by halfempty** [comment]
As opposed to reverse-chronological

**Comment by swambold6** [comment]
@halfempty When do you think you'll have a chance to look in to this?  Sonia was asking me about it again today.  Thanks!

**Comment by halfempty** [comment]
@swambold6 On it!

**Comment by halfempty** [comment]
@swambold6 Okay, this is done. Here's an example:

https://clyffordstillmuseum.org/event/one-painting-at-a-time-molina-speaks-ph-268-1955-and-ph-921-1955/

Let me know if you see any issues. If yes, please reopen. Thanks!

**Comment by swambold6** [comment]
Fantastic!  Thanks!

On Tue, Jan 5, 2016 at 1:20 PM, Marty Spellerberg <notifications@github.com>
wrote:

> Closed #135 <https://github.com/stillmuseum/patricia/issues/135>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/135#event-506343593>.
>



-- 
Best regards,
Sarah Wambold

swambold.com
