### ISSUE TITLE
Recurring Date messiness

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#136]
We created some recurring events today and this is how the front-end looks...

![screen shot 2015-12-10 at 4 01 42 pm](https://cloud.githubusercontent.com/assets/7491703/11732283/c93fcbd6-9f5f-11e5-8727-f37679c6bc08.png)

Right now, we're using Recurring Events to create the series and then we're breaking apart the children so that we can alter the details for individual events. Once the recurrence is broken, it appears normal, of course. Could we get this cleaned up?

I'm not aware of a pressing need for this to be addressed urgently. However, everyone is working to get their programs in by Dec 16. It wouldn't surprise me if we need to address it that day, so perhaps you could plan accordingly.

**Comment by swambold6** [comment]
Hiya!  So now there's a pressing need for this to be addressed.  The MoxieU event will remain recurring...can we get rid of the messy text on the front end?

https://clyffordstillmuseum.org/?post_type=tribe_events&p=5068&preview=true

Remove: AN EVENT EVERY MONTH ON THE SAME DAY THAT LASTS 0 DAY(S) AND 0 HOUR(S), THE LAST OF WHICH WILL BEGIN ON NOVEMBER 8, 2016

**Comment by swambold6** [comment]
@halfempty Did you happen to look in to this yet?  It ended up not being an issue with the MoxieU event referenced above because we broke the parent/child relationships of the recurring events.  However, we have a similar need for our new Be Still My Heart programs.

https://dev.clyffordstillmuseum.org/event/be-still-my-heart-2/2016-02-12/
https://dev.clyffordstillmuseum.org/events/category/public-programs/

(Note that these are both in dev.)

**Comment by halfempty** [comment]
@swambold6 Can we just straight-up remove that text about recurrence? (That's the easiest thing.)

**Comment by swambold6** [comment]
You mean remove that from appearing on the front end, right?  Yes!  I think
that would be best.

On Fri, Feb 5, 2016 at 1:29 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> Can we just straight-up remove
> that text about recurrence? (That's the easiest thing.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/136#issuecomment-180545100>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 like  so:

https://dev.clyffordstillmuseum.org/events/category/public-programs/
