### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#137]
**@swambold6 says:**

I'm trying to use this site to analyze some visual data:
http://mkweb.bcgsc.ca/color-summarizer/?analyze

It won't let me use a url with https:// which rules out hosting it on my site or on the CSM's site.  I can't think of any other easy options.  Do you  have any ideas?

**Comment by halfempty** [comment]
@swambold6 I could pretty quickly make a non-https subdomain of CSM. You'd use FTP to upload. Would that work?

**Comment by swambold6** [comment]
Yeah, that would be fine.

What do you suggest I use to FTP?

**Comment by halfempty** [comment]
https://cyberduck.io/?l=en
