### ISSUE TITLE
Thumbnail glitch on program

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#139]
The preview thumbnail for this program https://clyffordstillmuseum.org/event/filmstill-troublemakers-the-story-of-land-art/ is not appearing as a square on the program page:

https://clyffordstillmuseum.org/events/category/public-programs/

@halfempty Could you look into this?

**Comment by halfempty** [comment]
@swambold6 It's 'cause the uploaded file was a GIF and so the new "check if it's a GIF and if so use original" code came into play. I re-saved as JPG and it's all good now.
