### ISSUE TITLE
For fun! Browser tabs that get lonely...

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#140]
Open this site in your browser (I'm using Chrome):
http://www.legworkstudio.com

Then open a new tab.  Do you see the messages in the browser tab for Legwork?

<img width="1072" alt="screen shot 2015-12-16 at 10 33 43 am" src="https://cloud.githubusercontent.com/assets/7491703/11848756/6b1836b6-a3e1-11e5-833d-55f21e118b99.png">

What is this and is it easy/quick?  :)

**Comment by halfempty** [comment]
Yeah, looks doable. Here's a discussion thread on the JavaScript involved...

http://stackoverflow.com/questions/23878277/change-content-of-title-tag-when-switching-to-other-open-tab-in-the-browser

**Comment by swambold6** [comment]
Awesome.  I'll touch base with John.  I think this would be fun.

On Wed, Dec 16, 2015 at 1:23 PM, Marty Spellerberg <notifications@github.com
> wrote:

> Yeah, looks doable. Here's a discussion thread on the JavaScript
> involved...
>
>
> http://stackoverflow.com/questions/23878277/change-content-of-title-tag-when-switching-to-other-open-tab-in-the-browser
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/140#issuecomment-165229577>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 I'd like to close this issue. But I'll create an "Ideas for Works on Paper" doc, put this in there, and we can evaluate if it's something that fits there.

**Comment by swambold6** [comment]
Sounds good. Thanks!

On Wed, Jun 15, 2016 at 12:02 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @swambold6 <https://github.com/swambold6> I'd like to close this issue.
> But I'll create an "Ideas for Works on Paper" doc, put this in there, and
> we can evaluate if it's something that fits there.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/140#issuecomment-226269799>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHJQd-RCRkhjOaRc_rCBUO3E-5jselYjks5qMD5HgaJpZM4G2uEh>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
