### ISSUE TITLE
Faux links on homepage

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#142]
The titles What's On; From the Collection; From the Archives look like links, but aren't.  Can they not have rollover behaviors like links?

![screen shot 2016-01-14 at 4 04 00 pm](https://cloud.githubusercontent.com/assets/7491703/12340530/9e5c132c-bad8-11e5-897d-b6729c1753a2.png)

**Comment by swambold6** [comment]
Update: If they can be linked to...

What's On: https://clyffordstillmuseum.org/events/
From the Collection: https://clyffordstillmuseum.org/about-the-collection/
From the Archives: https://clyffordstillmuseum.org/archives

Thanks!

**Comment by halfempty** [comment]
@swambold6 They are links!

**Comment by swambold6** [comment]
Great! Would you fix What's On? It's a 404.

And check the other two as well please. Thnx

On Thursday, January 14, 2016, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> They are links!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/142#issuecomment-171819898>
> .
>


-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
Done
