### ISSUE TITLE
Security: Use WordFence rather than iThemes Security Pro

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#143]

**Comment by halfempty** [comment]
@swambold6 Hey Sarah, the "legacy" site (redesign Phase 1) is still kicking around on the server. From a security perspective, I'd like it to go. May I delete?

**Comment by swambold6** [comment]
Yes, delete! We have a local copy saved on our server. For archival
purposes, whatever those might be.

On Wed, May 18, 2016 at 1:58 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Hey Sarah, the "legacy" site
> (redesign Phase 1) is still kicking around on the server. From a security
> perspective, I'd like it to go. May I delete?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/143#issuecomment-220140152>
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 Okay, it's gone.

I've also removed "Dev" because I want to set it up in a different way on the server (in a separate "webspace"), for increased security. But I won't do that yet-- I'll wait 'till we need dev again.
