### ISSUE TITLE
5th anniversary logo

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#146]
**@swambold6 says:**

> On Nov 18, we celebrate our 5th anniversary of opening the museum. (Is that a birthday?) This is the first I am seeing of the lockup design (and it's implementation on the website). Would love to know your thoughts on the logistics of putting this up.

**Comment by halfempty** [comment]
@swambold6 Would this be up just that single day? Maybe we could put it on a timer?

**Comment by swambold6** [comment]
Not a single day. Probably months. :(

...I'll find out...

On Fri, Jul 8, 2016 at 4:55 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> Would this be up just that
> single day? Maybe we could put it on a timer?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/146#issuecomment-231491759>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHJQd0T-N3n8_8JVIQnmuD96P0aZMiXFks5qTtVrgaJpZM4JIdf->
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com
