### ISSUE TITLE
Privacy Policy link

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#149]
@halfempty Can you add a link to this Privacy Policy page in the bottom footer of our site...

<img width="1430" alt="screen shot 2016-08-19 at 1 20 08 pm" src="https://cloud.githubusercontent.com/assets/7491703/17821602/b43819f6-660f-11e6-908a-de608bdd668d.png">

We're out of room in the menu-based footer and this seems like more fine print to me, yeah?

**Comment by swambold6** [comment]
https://clyffordstillmuseum.org/privacy-policy/

**Comment by halfempty** [comment]
Done
