### ISSUE TITLE
Related Events question

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#151]
Hi there, I received a request to relate the exhibition Repeat/Recreate (https://clyffordstillmuseum.org/replicas) with the event listed here https://clyffordstillmuseum.org/event/one-painting-at-a-time-geoff-van-dyke-ph-929-1974/ (it is a past event). When I try to edit the Exhibition post, I can't access the Event—it isn't listed as available in the Related Events box. I can go to the Event post and connect it with the Exhibition, and the link to the exhibition appears on the Event page, but the counterpart link does not appear on the Exhibition post.

Is this a bug or meant to be this way? I assume the problem is because the Event is passed.

**Comment by halfempty** [comment]
@swambold6 This is a bug in the Events plugin. I reported it to them, I think, last year
