### ISSUE TITLE
Photo resizing?

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#152]
@halfempty I added an inline photo to this page:
https://clyffordstillmuseum.org/exhibition/clyfford-still-the-works-on-paper/

Is the photo supposed to resize to be the column width, or is it displaying correctly here? (I think it's correct, but I just want to be sure.)

![screen shot 2016-10-31 at 10 31 52 am](https://cloud.githubusercontent.com/assets/7491703/19862268/30815b84-9f55-11e6-91ad-bdf603f616ef.png)

**Comment by halfempty** [comment]
@swambold6 This is correct.
