### ISSUE TITLE
Same entry to E-news submission over and over and over

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#154]
@halfempty 

One email address keeps getting entered into our eNews sign-up on the website over and over. Five times this morning, 11 times yesterdayday, all from helenburroughs@comcast.net. Any thoughts on whether or not this represents some kind of security threat?

John says this same thing happened in the spring. I don't recall...do you? Also, we've been having problems with comcast addresses receiving emails from us. Not sure if this is related?

**Comment by halfempty** [comment]
@swambold6 I've enabled "Anit-spam honeypot". Hopefully that will help!
