### ISSUE TITLE
Update the Museum Rentals Page

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#157]
**@swambold6 says:**

> We'd like to use this same template design as Collection and Archives for a Rentals page
Where we are using "Objects" for the individual art objects in Collection and Archives, we'd use the same post type to create a gallery of event photos.

**Comment by halfempty** [comment]
Meeting notes:

- Discussed openness to evaluating how to contextualize Rentals on the site, beyond simple template update;
- Rentals is now existing in two places: "Private Events" and "Museum Rental";
- "Private events" is a nice presentation, but the link to "Museum Rental" gets lost;
- If we add a new Photos template area, it will be developed specifically as a photo gallery (even if the front-end presentation takes cues from Archive, it won't use a Custom Post Type)

**Comment by swambold6** [comment]
@halfempty I'd be happy for us to move forward on this per last week's discussion. What more information do you need from me?

**Comment by halfempty** [comment]
![image](https://cloud.githubusercontent.com/assets/775543/21625534/bec85bc8-d1d1-11e6-887a-af65ae9c4edb.png)

**Comment by halfempty** [comment]
One of these:
![image](https://cloud.githubusercontent.com/assets/775543/21625660/4b1d47aa-d1d2-11e6-99b1-aef91a3bd46a.png)

**Comment by halfempty** [comment]
@swambold6 Some progress:

https://clyffordstillmuseum.org/rentals-revised/

Now, it's not 100% done. But I wanted to show you, to get your sense whether the concept is working. Specifically, the gallery link?

**Comment by swambold6** [comment]
@halfempty Looks good! Just showed Lydia...she's happy. I can't see anything we'd like changed at this point. Onwards!

**Comment by swambold6** [comment]
@halfempty I can't find Rentals (Revised) in the Parent options. Am I blind?

<img width="297" alt="screen shot 2017-02-01 at 10 18 38 am" src="https://cloud.githubusercontent.com/assets/7491703/22517893/e7904488-e867-11e6-9fb9-8bb641f001f3.png">

**Comment by swambold6** [comment]
@halfempty Using Pages page worked.

Would you fix the tables for me? (First column needs to be wider, please.)
