### ISSUE TITLE
Quick fix on the table

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#160]
@halfempty Should be a quick fix...

John would like more space added after the times in the table on the symposium page so that the columns don't butt up against eachother as much:
https://clyffordstillmuseum.org/nyc?preview=true

[DraftEventPage_v3.pdf](https://github.com/stillmuseum/patricia/files/646736/DraftEventPage_v3.pdf)

He tried adding non-breaking space, but the cms strips it out. Can you help?

**Comment by halfempty** [comment]
@swambold6 Done
