### ISSUE TITLE
anchored links?

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#164]
@halfempty Looks like I can't set anchored links in WP anymore??

Trying to link an instance of Photography Shoot Passes to the Heading for that section on this page:
https://clyffordstillmuseum.org/?page_id=7141&preview=true

**Comment by halfempty** [comment]
@swambold6 Are you saying there used to be an interface for it, but no longer?

**Comment by swambold6** [comment]
Yes exactly. You used to be able to set an anchor with an anchor icon in
the toolbar and then link to it. When I try to add html to the text editor
it gets stripped out.

**Comment by halfempty** [comment]
@swambold6 Catch me up, 'cause I never see the "Visual" editor-- Has it changed in the latest version of WP, with this functionality removed?

What if you switch over to the "Text" (HTML) view? Can you edit there? (I know you know the HTML. If it were someone else I wouldn't ask.)

There's a plugin for customizing the Visual editor, but I'd only want to add it if we really need to 'cause it's a bit messy.

**Comment by swambold6** [comment]
I'd be happy to use html but it gets stripped out when I try. ?
