### ISSUE TITLE
Tag padding

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#167]
![image](https://cloud.githubusercontent.com/assets/775543/21625193/2e370fe2-d1d0-11e6-8d0f-4492b2b697e9.png)

**Comment by swambold6** [comment]
Looks like this is still an issue:
![screen shot 2017-05-05 at 11 28 48 am](https://cloud.githubusercontent.com/assets/7491703/25756992/0f461784-3186-11e7-8989-ded20a2f84cc.png)

**Comment by halfempty** [comment]
Done
