### ISSUE TITLE
Photo Gallery Template

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#168]
An aspect of the Rentals work.

- A template containing many images.
- Images are tagged, and filtered based on these.
- Click thumbnails to expand in a lightbox

**Comment by swambold6** [comment]
@halfempty 

Tags taxonomy:

(Building)
Galleries
Lobby
Forecourt

(Event Type)
Weddings
Corporate Events

(Season)
Summer
Winter

Will users have the ability to select multiple tags? So like, Weddings and Summer?

**Comment by halfempty** [comment]
@swambold6 Progress here:

https://clyffordstillmuseum.org/museum-rentals-photo-gallery/

Let's discuss!

**Comment by swambold6** [comment]
@halfempty I assume we will discuss at our meeting today.

**Comment by halfempty** [comment]
@swambold6 Okay, icons added here. If it looks good to you, feel free to begin using this template on the site.

![image](https://cloud.githubusercontent.com/assets/775543/22184905/d6d4b92c-e0a0-11e6-9eb9-f580038c7151.png)

https://clyffordstillmuseum.org/museum-rentals-photo-gallery/
