### ISSUE TITLE
Dev to Live Update

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#174]
- [x] https://dev.clyffordstillmuseum.org/research-center/
- [x] https://dev.clyffordstillmuseum.org/publications/
- [x] https://dev.clyffordstillmuseum.org/museum-rental/
- [x] https://dev.clyffordstillmuseum.org/museum-rentals-photo-gallery/
- [x] https://dev.clyffordstillmuseum.org/rental-inquiry/
- [x] https://dev.clyffordstillmuseum.org/rental-inquiry-received/
- [x] https://dev.clyffordstillmuseum.org/photography-policy/
- [x] https://dev.clyffordstillmuseum.org/photography-video-shoot-application-form
- [x] https://dev.clyffordstillmuseum.org/photography-application-received/
- [x] https://dev.clyffordstillmuseum.org/channel
- [x] https://dev.clyffordstillmuseum.org/resources/

Very minor changes:

- [x] https://dev.clyffordstillmuseum.org/archives
- [x] https://dev.clyffordstillmuseum.org/clyfford-still/

**Comment by halfempty** [comment]
@swambold6 Research center done, please check:

https://dev.clyffordstillmuseum.org/research-center/
https://clyffordstillmuseum.org/research-center/

**Comment by halfempty** [comment]
@swambold6 Publications done, please check:

https://dev.clyffordstillmuseum.org/publications/
https://clyffordstillmuseum.org/publications/

**Comment by halfempty** [comment]
@swambold6 The Photo Application form and confirmation don't appear to have changed at all. I've looked closely at the form settings.

https://dev.clyffordstillmuseum.org/photography-video-shoot-application-form
https://clyffordstillmuseum.org/photography-video-shoot-application-form

https://dev.clyffordstillmuseum.org/photography-application-received/
https://clyffordstillmuseum.org/photography-application-received/

**Comment by halfempty** [comment]
@swambold6 Photo policy doesn't appear to have changed. It does look, however, like this is linked in the footer on Live but not Dev

https://dev.clyffordstillmuseum.org/photography-policy/
https://clyffordstillmuseum.org/photography-policy/

**Comment by halfempty** [comment]
@swambold6 Rental inquiry form does not appear to have changed

https://dev.clyffordstillmuseum.org/rental-inquiry/
https://clyffordstillmuseum.org/rental-inquiry/

https://dev.clyffordstillmuseum.org/rental-inquiry-received/
https://clyffordstillmuseum.org/rental-inquiry-received/

**Comment by halfempty** [comment]
@swambold6 Photo gallery done:

https://dev.clyffordstillmuseum.org/museum-rentals-photo-gallery/
https://clyffordstillmuseum.org/museum-rentals-photo-gallery/

**Comment by halfempty** [comment]
@swambold6 Rentals done:

https://dev.clyffordstillmuseum.org/museum-rental/
https://clyffordstillmuseum.org/museum-rental/

**Comment by halfempty** [comment]
@swambold6 Channel done:

https://dev.clyffordstillmuseum.org/channel
https://clyffordstillmuseum.org/channel/

And I took the liberty of adding a Sidebar menu

**Comment by halfempty** [comment]
@swambold6 And, last but not least...

https://dev.clyffordstillmuseum.org/resources/
https://clyffordstillmuseum.org/resources/

Again, I took the liberty of adding a Sidebar menu

**Comment by swambold6** [comment]
@halfempty Looks all done to me! Thanks!
