### ISSUE TITLE
Exhibitions: Mockup of Upcoming / Past

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#179]

**Comment by halfempty** [comment]
@swambold6 Here's the concept I floated last week... but I don't think it's fully successful. Can we brainstorm more?

![exhibitions1a](https://cloud.githubusercontent.com/assets/775543/25833993/adccef02-343a-11e7-9238-0ef6930df72c.jpg)

![exhibitions1b](https://cloud.githubusercontent.com/assets/775543/25833997/b08bd726-343a-11e7-8382-c535aa1162cc.jpg)

**Comment by halfempty** [comment]
@swambold6 Okay, I think this is done. Take a look?

https://dev.clyffordstillmuseum.org/exhibitions/

**Comment by swambold6** [comment]
@halfempty Dean is very happy with this. Please put it into effect!
