### ISSUE TITLE
Volunteer form linking to Still Life page

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#188]
@halfempty The button to the Volunteer Application page is opening the Still Life blog...

https://clyffordstillmuseum.org/opportunities#volunteer

Everything I've checked in WP appears to be correct. I could muddle around with it to see if there's a workaround, but I'd like for you to take a look in case there's something more sinister going on. :) Do you have time to look at this today? If not, I'll muddle...

**Comment by halfempty** [comment]
@swambold6 Weird. Fixed it by messing with the slug, though I don't know what's causing the underlying issue.
