### ISSUE TITLE
Calendar "Grid" View

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#3]

**Comment by halfempty** [comment]
@swambold6 Status update on this:

Before beginning work on the Grid view itself, I'm updating the calendar to the latest version-- from v. 3.7 to 3.9. With this update, even though the version numbers are small, some things have broken. So I've been going back and forth with the Calendar folks, to get things working again.

Once that's done, I'll move to the Grid view. My Grid code was written circa v 2.5, so I'm expecting a large number of bugs will appear and need to be addressed.

**Comment by swambold6** [comment]
Okie-dokie...thanks for the update!

On Fri, Mar 27, 2015 at 3:06 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Status update on this:
>
> Before beginning work on the Grid view itself, I'm updating the calendar
> to the latest version-- from v. 3.7 to 3.9. With this update, even though
> the version numbers are small, some things have broken. So I've been going
> back and forth with the Calendar folks, to get things working again.
>
> Once that's done, I'll move to the Grid view. My Grid code was written
> circa v 2.5, so I'm expecting a large number of bugs will appear and need
> to be addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/3#issuecomment-87091653>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by swambold6** [comment]
You mentioned yesterday that the MCA had the option to run a beta version of 4.0.  Could that be an option for CSM?  Get a beta version of 4.0 installed on dev, on which you can build the grid?  Or is 4.0 too incomplete/buggy at this point for that to be an option?

**Comment by halfempty** [comment]
It's not publicly available. The MCA was going to support that development financially.

**Comment by swambold6** [comment]
Ah.  Got it.  Thanks.

On Tue, Mar 31, 2015 at 11:20 AM, Marty Spellerberg <
notifications@github.com> wrote:

> It's not publicly available. The MCA was going to support that development
> financially.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/3#issuecomment-88177170>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by swambold6** [comment]
John says run the old version until 4.0, then build the grid view when 4.0 is released.  Ok?

**Comment by halfempty** [comment]
Perfect! I haven't heard back from the folks about those bugs and 4.0 (and I might not-- those support forum guys might not have the authority to say much). I'll evaluate it when it comes out, and we'll report to John on its stability.

**Comment by swambold6** [comment]
Sounds good.  Keep me posted.


On Tue, Mar 31, 2015 at 4:58 PM, Marty Spellerberg <notifications@github.com
> wrote:

> Perfect! I haven't heard back from the folks about those bugs and 4.0 (and
> I might not-- those support forum guys might not have the authority to say
> much). I'll evaluate it when it comes out, and we'll report to John on its
> stability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/3#issuecomment-88277742>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 Do we still want a grid view on Events? This is probably more of an "M"-sized task now that we've upgraded the plugin.

**Comment by swambold6** [comment]
@halfempty This page is the 12th most viewed page. So it's getting some significant visits. That said, I've not heard even one time that people expect it to be a calendar grid. So I say close it. If I get feedback to the contrary at some point, we will reopen for sure.
