### ISSUE TITLE
Related content

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#62]

**Comment by halfempty** [comment]
It seems we've decided not to do this? Can we close this issue?

**Comment by swambold6** [comment]
Let me double-check the Phase 2 SOW before we close it.  Have to run
now...will get to it tonight or first thing tomorrow morning...

On Tue, Mar 31, 2015 at 5:14 PM, Marty Spellerberg <notifications@github.com
> wrote:

> It seems we've decided not to do this? Can we close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/62#issuecomment-88279893>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by swambold6** [comment]
Correct.  Please close.

Thanks!

On Tue, Mar 31, 2015 at 5:21 PM, Sarah Wambold <swambold@gmail.com> wrote:

> Let me double-check the Phase 2 SOW before we close it.  Have to run
> now...will get to it tonight or first thing tomorrow morning...
>
> On Tue, Mar 31, 2015 at 5:14 PM, Marty Spellerberg <
> notifications@github.com> wrote:
>
>> It seems we've decided not to do this? Can we close this issue?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stillmuseum/patricia/issues/62#issuecomment-88279893>
>> .
>>
>
>
>
> --
> Best regards,
> Sarah Wambold
>
> swambold.com
>



-- 
Best regards,
Sarah Wambold

swambold.com
