### ISSUE TITLE
"Archive" on Homepage

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#7]
Let’s talk about the logic for pulling items for these rows. 

For What’s On, will it be a combo of Events and Exhibitions? Right now I’ve got the four next upcoming Events.

For Archive… what pages are these, exactly? Blogs? Or pages from some new-ish Archive section?

**Comment by halfempty** [comment]
@swambold6 Please take a look at this-- Archive on the homepage. It's a random selection of 4:

https://dev.clyffordstillmuseum.org/

**Comment by swambold6** [comment]
I LOVE this!  Looks great!

Here's a question...I notice the thumbnails are not linked.  Can they easily be linked like the titles are?

**Comment by halfempty** [comment]
@ScottReinhard Okay, yeah, it was weird, none of the homepage thumbs were linked. But I've now linked them.

**Comment by swambold6** [comment]
Thanks for doing that!  I'll send John a note tonight to alert him to the new organization of the Archives and send a screenshot of this just to give him a heads up.  I'll let you know when to commit the changes to the public site, ok?

**Comment by swambold6** [comment]
Ooof, sorry...one more question...how is the selection of items handled?  It's a random selection of four items, right?  It appears it may be limited to one item per category...is that right?  Is it a new selection every time the page loads?  Thanks for the additional details.

**Comment by halfempty** [comment]
@swambold6 Can we roll a bunch of these Archive changes in to launch together? It'll make it easier to move quickly through them.

**Comment by halfempty** [comment]
@swambold6 Random 4 on page generation.

**Comment by swambold6** [comment]
Yep, sounds good.  I won't mention the Archive items on the homepage yet,
then.

On Mon, Mar 9, 2015 at 8:54 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> Random 4 on page generation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/7#issuecomment-77987231>.
>



-- 
Best regards,
Sarah Wambold

swambold.com
