### ISSUE TITLE
Photo credits for Story Page Templates

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#74]
photo credits on homepage and architecture pages???

**Comment by halfempty** [comment]
@swambold6 Remind me about this one? 

Right now we're hard-coding captions into the footer. Do we want to keep this placement, but just have them be managed via WP? Or are we also going to attach them to their images?

**Comment by swambold6** [comment]
I don't know.  I'll ask John...

On Wed, Jan 14, 2015 at 12:31 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @swambold6 <https://github.com/swambold6> Remind me about this one?
>
> Right now we're hard-coding captions into the footer. Do we want to keep
> this placement, but just have them be managed via WP? Or are we also going
> to attach them to their images?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/74#issuecomment-69976180>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by swambold6** [comment]
Question: the alternative to pulling the captions from the Media files in WP would be what?  To have a widget for each, or to have a field on the story page template for captions?

**Comment by swambold6** [comment]
John says: 

1) captions to appear below the footer, as they are now.
2) a single text field on the story page in the CMS that allows you to control the captions and how they appear.

Ok?

**Comment by halfempty** [comment]
Done
