### ISSUE TITLE
Blog excerpt formatting

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#84]
@halfempty One more question...on the category page for the blog, the paragraph previews run all the text together.  This is problematic when there is a guest blogger and they have a byline at the top:

![screen shot 2014-09-20 at 6 19 26 pm](https://cloud.githubusercontent.com/assets/7491703/4346966/33da5f00-4125-11e4-9725-56ceaec39ae2.png)

This isn't a huge concern, but if you have any easy solutions, let me know.

**Comment by halfempty** [comment]
@swambold6 I've installed a plugin, "Advanced Excerpt," that might help with this. It's at Settings -> Excerpt. Take a look, tweak the settings and see if it does?

**Comment by swambold6** [comment]
On the public site or on the dev site?

**Comment by swambold6** [comment]
Nevermind...

Seems to have worked perfectly already:

![screen shot 2015-03-13 at 12 59 33 pm](https://cloud.githubusercontent.com/assets/7491703/6645291/dfb22892-c980-11e4-8fdc-38d1238aeda6.png)
