### ISSUE TITLE
Recurring Description for Events?

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#86]
@halfempty Looks like there's not yet a front-end implementation for a custom description of recurring events, eh?

http://dev.clyffordstillmuseum.org/wp-admin/post.php?post=2733&action=edit

![screen shot 2014-09-21 at 2 37 19 pm](https://cloud.githubusercontent.com/assets/7491703/4349950/25ae620a-41cf-11e4-975b-eaa80d8cd157.png)

![screen shot 2014-09-21 at 2 38 06 pm](https://cloud.githubusercontent.com/assets/7491703/4349955/38585dd4-41cf-11e4-8c73-c6e2a3ef7e30.png)

**Comment by halfempty** [comment]
@swambold6 I've re-enabled the code I was working on for this. Now I'm having trouble figuring out what's broken about it? Will you put Recurrence Description through the ringer on Dev? Thanks!

http://dev.clyffordstillmuseum.org/events/category/public-programs/

**Comment by swambold6** [comment]
Seems to be working (although it's not going to do exactly what John
expects it to...but that can be mitigated through explaining it).

One thing I notice though...  Do you see on this event the line that says,
"Until January 14, 2015"?  Where is that coming from?

http://dev.clyffordstillmuseum.org/event/csm-spring-keynote-roberta-smith-and-jerry-saltz/

Is that a bug or something??


On Wed, Jan 14, 2015 at 12:29 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @swambold6 <https://github.com/swambold6> I've re-enabled the code I was
> working on for this. Now I'm having trouble figuring out what's broken
> about it? Will you put Recurrence Description through the ringer on Dev?
> Thanks!
>
> http://dev.clyffordstillmuseum.org/events/category/public-programs/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/86#issuecomment-69975699>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 Yeah, okay, that's the bug, thank you.

What does John expect it to do? I'd like to make it how he wants it, if we can.

**Comment by halfempty** [comment]
@swambold6 okay, I think I've the bug worked out. Let me know if you still see weirds. But do let me know if there's anything we can do to make it more like John's expectation.

**Comment by halfempty** [comment]
@swambold6 I've applied this one to live, and will close this. But if John wants the behavior changed in any way, feel free to reopen.

**Comment by swambold6** [comment]
@halfempty I'm confused about this one:
http://clyffordstillmuseum.org/wp-admin/post.php?post=3392&action=edit

Help me figure out what's going on here... The event is set up as recurring, repeating once.  However Recurring Description doesn't appear, neither does the child event, and when you look for it in the CMS, it doesn't say it's recurring.  What's happening here?
