### ISSUE TITLE
Archive categories

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#88]
@halfempty I'm adding categories for the archives per our discussion yesterday.  I've made them children of the Archives category, but I see that the 1920s, 30s, etc, are not children of Collection (and in fact, there is no Collection category), so I'm not sure I did this right.  Let me know.

Also, I'm putting this down as post-launch...no rush.

**Comment by halfempty** [comment]
@swambold6 Okay, I think this is in. But you'll have to remind me! Is this what we're looking for?

http://dev.clyffordstillmuseum.org/archives

**Comment by swambold6** [comment]
Yes!  This looks great.  Shall I run this by John?  (Has he ever accessed the dev site?)  

Also, I'll try to source more items for each category before we release it.

**Comment by swambold6** [comment]
One more question...do CSM users have the ability to add Archive categories and have them appear on the front-end?  Or are the hard coded?

**Comment by halfempty** [comment]
@swambold6 This one I've already applied to the site, actually. Yes, sub-categories can be added via the Dashboard.

**Comment by swambold6** [comment]
Super!  Done then, yes?
