### ISSUE TITLE
Audio/Video players for Archive items

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#89]
I'll research.

Jessie suggests this: http://create.blubrry.com/resources/powerpress/

**Comment by halfempty** [comment]
@swambold6 On the "Edit Object" screen of DEV, there's now a choice for Audio and Video objects. Do you have some assets for this? Will you create a couple of test objects for each, which I can use to develop with?

If you can, please set a Featured Image for them. I'm thinking they'll appear as thumbnails, and also before the media has begun to play. I suppose we'll also need fallbacks, for assets that have no images (especially audio), but custom images would be best, of course.

 Thank you!

**Comment by swambold6** [comment]
Absolutely I can source some things.  (In fact, I think I already have some...)

A question first, though: It seems to me that we left off the conversation expecting to host the actual assets elsewhere (like Vimeo or Soundcloud).  Is that your expectation?  Or do you want me to upload the assets directly in to WP?

**Comment by halfempty** [comment]
@swambold6 I was thinking it would be: For video, Vimeo; for audio, direct upload of MP3s. So that's what I've prepared for. Soundcloud would be good too, but isn't there a monthly fee?

**Comment by swambold6** [comment]
Video here:
https://dev.clyffordstillmuseum.org/object/still-in-motion/

Audio here:
https://dev.clyffordstillmuseum.org/object/chopin-study/

I don't have the video asset so could grab a proper still for the Featured Image, but made a down-and-dirty screenshot for a placeholder.  No Featured Image for the audio...let me know if you want me to put something as a dummy or if you'd prefer to develop a boilerplate image for audio (which is probably a good idea).

**Comment by halfempty** [comment]
@swambold6 Okay, audio and video now working:

https://dev.clyffordstillmuseum.org/archives#selections

**Comment by swambold6** [comment]
Looks great!  The audio file isn't playing for me when I click through.
Any tricks to it?

On Mon, Mar 23, 2015 at 9:56 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> Okay, audio and video now
> working:
>
> https://dev.clyffordstillmuseum.org/archives#selections
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/89#issuecomment-85330160>.
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
Shouldn't be. It's a standard widget generated by WP.

**Comment by swambold6** [comment]
Seems to be a Safari issue then.  ?

Otherwise, looks good!

**Comment by halfempty** [comment]
It appears to be a conflict with SSL. Drat.

**Comment by halfempty** [comment]
This thread...

http://stackoverflow.com/questions/21212292/issue-with-mediaelement-js-stuck-at-loading

Indicates it might have to do with the SSL error on staging. I suggest we proceed with deploying that code live, and see if the bug persists.

**Comment by swambold6** [comment]
Sounds good. When do you expect to be able to deploy the code? I need a day to get the ordering of archive items set and to prepare a note to John.

**Comment by halfempty** [comment]
@swambold6 Whenever you're ready. I've saved it to a branch and will proceed with Calendar stuff.

**Comment by swambold6** [comment]
Have you applied this code?  CSM Collection Options does not seem to be there?

**Comment by halfempty** [comment]
Okay, better now?

**Comment by swambold6** [comment]
Yep!  Thanks!
