### ISSUE TITLE
Donation info for Archives

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#90]
Jessie: Additionally, I need to revisit the copy for the archive page...I was thinking of including a section about donating materials, similar to this:
http://www.jfklibrary.org/Research/Research-Services/Donating-your-materials.aspx

**Comment by halfempty** [comment]
@swambold6 There's not anything needed from me on this one, right?

**Comment by swambold6** [comment]
Right.  This isn't really in the scope of Phase 2.  It's a wish list item for Jessie (in Archives), I just don't want to lose track of it.

**Comment by halfempty** [comment]
@swambold6 Is this one still active?

**Comment by swambold6** [comment]
@halfempty I haven't heard one more word about it. Let's close it. (shhhhh...)
