### ISSUE TITLE
Collections ordering question

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#95]
@halfempty I notice the ordering on the collections posts are based on publishing date/time.  I can go back in and reorder things manually...unless there is an easy drag-and-drop functionality that can be added.  You tell me...I'm fine either way.

**Comment by halfempty** [comment]
@swambold6 Okay, I've modified Objects so that they are sorted by Menu Order (on Dev).  When we apply this code to live, the order of the objects will go all out-of-wack, and they'll have to be reset using the new setting.

**Comment by swambold6** [comment]
Ok.  Give me a sense of the timeline for applying all these collection changes.  You want to do all the collection stuff all at once, right?  Any thoughts on when that might happen so I can make myself available to do this type of clean-up work?

**Comment by swambold6** [comment]
To confirm before I screw everything up...I should reorder using drag-and-drop on the live site in prep for the code update to come.  And I should order things top-to-bottom in WP as I see them left-to-right, top-to-bottom on the live site.  Right?

**Comment by halfempty** [comment]
Yes and yes!

**Comment by swambold6** [comment]
Done!  All the drafts I have in are at the bottom, but everything's been sorted.

**Comment by halfempty** [comment]
Cool. Should I apply that batch of updates?

**Comment by swambold6** [comment]
Yep!  Go!

On Mon, Mar 30, 2015 at 3:15 PM, Marty Spellerberg <notifications@github.com
> wrote:

> Cool. Should I apply that batch of updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/95#issuecomment-87833583>.
>



-- 
Best regards,
Sarah Wambold

swambold.com
